#!/bin/bash
set -ex

find . \
      \( -iname '*.out' -o -iname '*.toc' -o  -iname '*.log' -o -iname '*.aux' -o -iname '*.dvi' -o -iname '*.lol' -o \
      -iname '*.lof' -o -iname '*.run.xml' -o -iname '*.fdb_latexmk' -o -iname '*.fls' -o -iname '*.bbl' -o \
      -iname '*.bcf' -o -iname '*.blg' -o -iname '*.lot' -o -iname '*.nav' -o -iname '*.snm' \) \
      -exec rm -R {} +
docker run \
      --rm -t \
      --user="$(id -u):$(id -g)" \
      --net=none \
      -v "$(pwd):/tmp" \
      leplusorg/latex:1.0 \
      latexmk \
        -outdir=/tmp \
        -pdf /tmp/$@
docker run \
      --rm -t \
      --user="$(id -u):$(id -g)" \
      --net=none \
      -v "$(pwd):/tmp" \
      leplusorg/latex:1.0 \
      latexmk \
        -outdir=/tmp \
        -pdf /tmp/$@
find . \
      \( -iname '*.out' -o -iname '*.toc' -o  -iname '*.log' -o -iname '*.aux' -o -iname '*.dvi' -o -iname '*.lol' -o \
      -iname '*.lof' -o -iname '*.run.xml' -o -iname '*.fdb_latexmk' -o -iname '*.fls' -o -iname '*.bbl' -o \
      -iname '*.bcf' -o -iname '*.blg' -o -iname '*.lot' -o -iname '*.nav' -o -iname '*.snm' \) \
      -exec rm -R {} +

